# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ybenbrai <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/25 12:59:07 by ybenbrai          #+#    #+#              #
#    Updated: 2019/03/25 12:59:13 by ybenbrai         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all : $(NAME)

$(NAME) : 
	gcc -Wall -Wextra -Werror -o $(NAME) ft_display_file.c

clean :
	rm -f *.o

fclean : clean
	rm -f $(NAME)
